<?php
/*
READ ME FIRST!!!

This file was generated by the IntISP automatic installer.
Please do not change or edit this file directly.
If you need any assistance please visit our github
https://github.com/INTisp/INTisp
The Values in this file should be
DATABASE HOST: %HOSTNAME%
DATABASE USERNAME: %USERNAME%
DATABASE PASSWORD: %PASSWORD%
DATABASE NAME: %DATABASE%

Also Please remember all passwords in INTISP are secured with an advanced security hashing solution.
Passwords are securly encrypted using this salt.

SALT: %SALT%

If you are having any issues. Please change the debug variable. Please note that keeping this true can put your
server at risk as it exposes important server variables.

Thank You,
Adaclare Technologies

*/

$debug = false;
$host = '%HOSTNAME%';
$user = '%USERNAME%';
$pass = '%PASSWORD%';
$data = '%DATABASE%';
$salt = '%SALT%';
$lang = '%LANG%';
$webroot = '%WEBROOT%';
