#!/bin/sh
echo "Testing your system to make sure IntISP isnt broken..."
echo "1/3 System"
command -v php >/dev/null 2>&1 || { echo >&2 "I require php but it's not installed.  Aborting."; exit 1; }
echo "PHP     INSTALLED"
command -v mysql >/dev/null 2>&1 || { echo >&2 "I require mysql but it's not installed.  Aborting."; exit 1; }
echo "MYSQL     INSTALLED"
command -v a2ensite >/dev/null 2>&1 || { echo >&2 "I require apache but it's not installed.  Aborting."; exit 1; }
echo "APACHE     INSTALLED"
command -v python >/dev/null 2>&1 || { echo >&2 "I require python but it's not installed.  Aborting."; exit 1; }
echo "PYTHON     INSTALLED"
echo "2/3 Files"
if [ ! -f /var/www/html/interface/configdatabase.php ]; then
    echo "Database config not found!"
    else
    echo "DATABASE CONFIG     OK"
fi

if [ ! -f /var/www/html/interface/data/register ]; then
    echo "SERIAL # config not found!"
    else
    echo "SERIAL # CONFIG     OK"
fi
if [ ! -f /usr/local/bin/wvhost ]; then
    echo "WVHOST not found!"
    else
    echo "WVHOST     OK"
fi
echo "3/3 Daemon"
if lsof -Pi :8080 -sTCP:LISTEN -t >/dev/null ; then
    echo "WEBSERVER: RUNNING"
else
    echo "WEBSERVER: NOT RUNNING"
fi
echo "If everything is ok, intisp is running fine. The issue may be with the daemon. Please give our support this message if you have any issues."